
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jnone
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    int somatorio = 0;
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AO = new javax.swing.ButtonGroup();
        MRV = new javax.swing.ButtonGroup();
        MRM = new javax.swing.ButtonGroup();
        jBorda = new javax.swing.JPanel();
        jDiagnosticar = new javax.swing.JButton();
        jTituloAO = new javax.swing.JLabel();
        jAO4 = new javax.swing.JRadioButton();
        jAO3 = new javax.swing.JRadioButton();
        jAO2 = new javax.swing.JRadioButton();
        jAO1 = new javax.swing.JRadioButton();
        jTituloMRV = new javax.swing.JLabel();
        jMRV4 = new javax.swing.JRadioButton();
        jMRV5 = new javax.swing.JRadioButton();
        jMRV3 = new javax.swing.JRadioButton();
        jMRV2 = new javax.swing.JRadioButton();
        jMRV1 = new javax.swing.JRadioButton();
        jTituloMRM = new javax.swing.JLabel();
        jMRM6 = new javax.swing.JRadioButton();
        jMRM5 = new javax.swing.JRadioButton();
        jMRM4 = new javax.swing.JRadioButton();
        jMRM3 = new javax.swing.JRadioButton();
        jMRM2 = new javax.swing.JRadioButton();
        jMRM1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBorda.setBorder(javax.swing.BorderFactory.createTitledBorder("Escala de Glasgow"));

        jDiagnosticar.setText("Diagnosticar");
        jDiagnosticar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDiagnosticarActionPerformed(evt);
            }
        });

        jTituloAO.setText("Nível de Abertura Ocular");

        AO.add(jAO4);
        jAO4.setText("Olhos abrem espontaneamente");
        jAO4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAO4ActionPerformed(evt);
            }
        });

        AO.add(jAO3);
        jAO3.setText("Olhos abrem ao comando verbal");
        jAO3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAO3ActionPerformed(evt);
            }
        });

        AO.add(jAO2);
        jAO2.setText("Olhos abrem por estímulo doloroso");
        jAO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAO2ActionPerformed(evt);
            }
        });

        AO.add(jAO1);
        jAO1.setText("Olhos não abrem por nenhum motivo");
        jAO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAO1ActionPerformed(evt);
            }
        });

        jTituloMRV.setText("Nível de Resposta Verbal");

        MRV.add(jMRV4);
        jMRV4.setText("Confuso");
        jMRV4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRV4ActionPerformed(evt);
            }
        });

        MRV.add(jMRV5);
        jMRV5.setText("Orientado");
        jMRV5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRV5ActionPerformed(evt);
            }
        });

        MRV.add(jMRV3);
        jMRV3.setText("Palavras inapropriadas");
        jMRV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRV3ActionPerformed(evt);
            }
        });

        MRV.add(jMRV2);
        jMRV2.setText("Sons ininteligíveis");
        jMRV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRV2ActionPerformed(evt);
            }
        });

        MRV.add(jMRV1);
        jMRV1.setText("Ausente");
        jMRV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRV1ActionPerformed(evt);
            }
        });

        jTituloMRM.setText("Nível de Resposta Motora");

        MRM.add(jMRM6);
        jMRM6.setText("Obedece ordens verbais");
        jMRM6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRM6ActionPerformed(evt);
            }
        });

        MRM.add(jMRM5);
        jMRM5.setText("Localiza estímulo doloroso");
        jMRM5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRM5ActionPerformed(evt);
            }
        });

        MRM.add(jMRM4);
        jMRM4.setText("Retirada inespecífica à dor");
        jMRM4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRM4ActionPerformed(evt);
            }
        });

        MRM.add(jMRM3);
        jMRM3.setText("Padrão flexor à dor");
        jMRM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRM3ActionPerformed(evt);
            }
        });

        MRM.add(jMRM2);
        jMRM2.setText("Padrão extensor à dor");
        jMRM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRM2ActionPerformed(evt);
            }
        });

        MRM.add(jMRM1);
        jMRM1.setText("Sem resposta motora");
        jMRM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRM1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jBordaLayout = new javax.swing.GroupLayout(jBorda);
        jBorda.setLayout(jBordaLayout);
        jBordaLayout.setHorizontalGroup(
            jBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBordaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTituloAO, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jAO4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jAO3, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                    .addComponent(jAO2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAO1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBordaLayout.createSequentialGroup()
                        .addComponent(jMRV5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jBordaLayout.createSequentialGroup()
                        .addComponent(jMRV4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jBordaLayout.createSequentialGroup()
                        .addComponent(jMRV3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jBordaLayout.createSequentialGroup()
                        .addGroup(jBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jBordaLayout.createSequentialGroup()
                                .addComponent(jMRV2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addComponent(jMRV1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(jBordaLayout.createSequentialGroup()
                        .addComponent(jTituloMRV, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)))
                .addGroup(jBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMRM6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jMRM5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jMRM4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jBordaLayout.createSequentialGroup()
                        .addGroup(jBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jMRM3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBordaLayout.createSequentialGroup()
                                    .addGroup(jBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jMRM1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jMRM2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(27, 27, 27)))
                            .addComponent(jTituloMRM, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBordaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDiagnosticar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(315, 315, 315))
        );
        jBordaLayout.setVerticalGroup(
            jBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBordaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTituloAO)
                    .addComponent(jTituloMRV)
                    .addComponent(jTituloMRM))
                .addGap(18, 18, 18)
                .addGroup(jBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAO4)
                    .addComponent(jMRV5)
                    .addComponent(jMRM6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAO3)
                    .addComponent(jMRV4)
                    .addComponent(jMRM5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAO2)
                    .addComponent(jMRV3)
                    .addComponent(jMRM4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAO1)
                    .addComponent(jMRV2)
                    .addComponent(jMRM3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMRV1)
                    .addComponent(jMRM2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jMRM1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDiagnosticar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBorda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBorda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAO4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAO4ActionPerformed
        // TODO add your handling code here:
        somatorio += 4;
    }//GEN-LAST:event_jAO4ActionPerformed

    private void jMRV4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRV4ActionPerformed
        // TODO add your handling code here:
        somatorio += 4;
    }//GEN-LAST:event_jMRV4ActionPerformed

    private void jMRV5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRV5ActionPerformed
        // TODO add your handling code here:
        somatorio += 5;
    }//GEN-LAST:event_jMRV5ActionPerformed

    private void jMRV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRV3ActionPerformed
        // TODO add your handling code here:
        somatorio += 3;
    }//GEN-LAST:event_jMRV3ActionPerformed

    private void jMRV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRV2ActionPerformed
        // TODO add your handling code here:
        somatorio += 2;
    }//GEN-LAST:event_jMRV2ActionPerformed

    private void jMRV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRV1ActionPerformed
        // TODO add your handling code here:
        somatorio += 1;
    }//GEN-LAST:event_jMRV1ActionPerformed

    private void jDiagnosticarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDiagnosticarActionPerformed
        // TODO add your handling code here:
        if(jAO1.isSelected()  == false && jAO2.isSelected()  == false && jAO3.isSelected()  == false && jAO4.isSelected()  == false ){
            JOptionPane.showMessageDialog(null, "Você não preencheu o Nível de Abertura Ocular");
            
        }
        
        if(jMRV1.isSelected() == false && jMRV2.isSelected() == false && jMRV3.isSelected() == false && jMRV4.isSelected() == false && jMRV5.isSelected() == false){
            JOptionPane.showMessageDialog(null, "Você não preencheu o Nível de Respota Verbal");
            
        }
        
        if(jMRM1.isSelected() == false && jMRM2.isSelected() == false && jMRM3.isSelected() == false && jMRM4.isSelected() == false && jMRM5.isSelected() == false && jMRM6.isSelected() == false ){
            JOptionPane.showMessageDialog(null, "Você não preencheu o Nível de Resposta Motora");
            
        }
        
        if(jAO1.isSelected()  == false && jAO2.isSelected()  == false && jAO3.isSelected()  == false && jAO4.isSelected()  == false || jMRV1.isSelected() == false && jMRV2.isSelected() == false && jMRV3.isSelected() == false && jMRV4.isSelected() == false && jMRV5.isSelected() == false || jMRM1.isSelected() == false && jMRM2.isSelected() == false && jMRM3.isSelected() == false && jMRM4.isSelected() == false && jMRM5.isSelected() == false && jMRM6.isSelected() == false){
            jLimparTudo();
        }
        
        switch(somatorio){
            case 3:
                JOptionPane.showMessageDialog(null, "O paciente possui 3 pontos na escala Glasgow;\nSe encontra em um estado de coma profundo;\nClassificado com trauma cranioencefálico grave.");
                jLimparTudo();
                break;
            case 4:
                JOptionPane.showMessageDialog(null, "O paciente possui 4 pontos na escala Glasgow;\nSe encontra em um estado de coma profundo;\nClassificado com trauma cranioencefálico grave.");
                jLimparTudo();
                break;
            case 5:
                JOptionPane.showMessageDialog(null, "O paciente possui 5 pontos na escala Glasgow;\nSe encontra em um estado de coma profundo;\nClassificado com trauma cranioencefálico grave.");
                jLimparTudo();
                break;
            case 6:
                JOptionPane.showMessageDialog(null, "O paciente possui 6 pontos na escala Glasgow;\nSe encontra em um estado de coma profundo;\nClassificado com trauma cranioencefálico grave.");
                jLimparTudo();
                break;
            case 7:
                JOptionPane.showMessageDialog(null, "O paciente possui 7 pontos na escala Glasgow;\nSe encontra em um estado de coma intermediário;\nClassificado com trauma cranioencefálico grave.");
                jLimparTudo();
                break;
            case 8:
                JOptionPane.showMessageDialog(null, "O paciente possui 8 pontos na escala Glasgow;\nSe encontra em um estado de coma intermediário;\nClassificado com trauma cranioencefálico grave.");
                jLimparTudo();
                break;
            case 9:
                JOptionPane.showMessageDialog(null, "O paciente possui 9 pontos na escala Glasgow;\nSe encontra em um estado de coma intermediário;\nClassificado com trauma cranioencefálico moderado.");
                jLimparTudo();
                break;
            case 10:
                JOptionPane.showMessageDialog(null, "O paciente possui 10 pontos na escala Glasgow;\nSe encontra em um estado de coma intermediário;\nClassificado com trauma cranioencefálico moderado.");
                jLimparTudo();
                break;
            case 11:
                JOptionPane.showMessageDialog(null, "O paciente possui 11 pontos na escala Glasgow;\nSe encontra em um estado de coma superficial;\nClassificado com trauma cranioencefálico moderado.");
                jLimparTudo();
                break;
            case 12:
                JOptionPane.showMessageDialog(null, "O paciente possui 12 pontos na escala Glasgow;\nSe encontra em um estado de coma superficial;\nClassificado com trauma cranioencefálico moderado.");
                jLimparTudo();
                break;
            case 13:
                JOptionPane.showMessageDialog(null, "O paciente possui 13 pontos na escala Glasgow;\nSe encontra em um estado de coma superficial;\nClassificado com trauma cranioencefálico leve.");
                jLimparTudo();
                break;
            case 14:
                JOptionPane.showMessageDialog(null, "O paciente possui 14 pontos na escala Glasgow;\nSe encontra em um estado de coma superficial;\nClassificado com trauma cranioencefálico leve.");
                jLimparTudo();
                break;
            case 15:
                JOptionPane.showMessageDialog(null, "O paciente possui 15 pontos na escala Glasgow;\nSe encontra dentro da normalidade;\nClassificado com trauma cranioencefálico leve.");
                jLimparTudo();
                break;
            default:
                JOptionPane.showMessageDialog(null, "Tente novamente");
                jLimparTudo();
                break;
            
    }
    }//GEN-LAST:event_jDiagnosticarActionPerformed

    public void jLimparTudo(){
        somatorio = 0;
        AO.clearSelection();
        MRM.clearSelection();
        MRV.clearSelection();
    }
    
    private void jMRM6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRM6ActionPerformed
        // TODO add your handling code here:
        somatorio += 6;
    }//GEN-LAST:event_jMRM6ActionPerformed

    private void jMRM5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRM5ActionPerformed
        // TODO add your handling code here:
        somatorio += 5;
    }//GEN-LAST:event_jMRM5ActionPerformed

    private void jMRM4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRM4ActionPerformed
        // TODO add your handling code here:
        somatorio += 4;
    }//GEN-LAST:event_jMRM4ActionPerformed

    private void jMRM3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRM3ActionPerformed
        // TODO add your handling code here:
        somatorio += 3;
    }//GEN-LAST:event_jMRM3ActionPerformed

    private void jMRM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRM2ActionPerformed
        // TODO add your handling code here:
        somatorio += 2;
    }//GEN-LAST:event_jMRM2ActionPerformed

    private void jMRM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRM1ActionPerformed
        // TODO add your handling code here:
        somatorio += 1;
    }//GEN-LAST:event_jMRM1ActionPerformed

    private void jAO3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAO3ActionPerformed
        // TODO add your handling code here:
        somatorio += 3;
    }//GEN-LAST:event_jAO3ActionPerformed

    private void jAO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAO2ActionPerformed
        // TODO add your handling code here:
        somatorio += 2;
    }//GEN-LAST:event_jAO2ActionPerformed

    private void jAO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAO1ActionPerformed
        // TODO add your handling code here:
        somatorio += 1;
    }//GEN-LAST:event_jAO1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AO;
    private javax.swing.ButtonGroup MRM;
    private javax.swing.ButtonGroup MRV;
    private javax.swing.JRadioButton jAO1;
    private javax.swing.JRadioButton jAO2;
    private javax.swing.JRadioButton jAO3;
    private javax.swing.JRadioButton jAO4;
    private javax.swing.JPanel jBorda;
    private javax.swing.JButton jDiagnosticar;
    private javax.swing.JRadioButton jMRM1;
    private javax.swing.JRadioButton jMRM2;
    private javax.swing.JRadioButton jMRM3;
    private javax.swing.JRadioButton jMRM4;
    private javax.swing.JRadioButton jMRM5;
    private javax.swing.JRadioButton jMRM6;
    private javax.swing.JRadioButton jMRV1;
    private javax.swing.JRadioButton jMRV2;
    private javax.swing.JRadioButton jMRV3;
    private javax.swing.JRadioButton jMRV4;
    private javax.swing.JRadioButton jMRV5;
    private javax.swing.JLabel jTituloAO;
    private javax.swing.JLabel jTituloMRM;
    private javax.swing.JLabel jTituloMRV;
    // End of variables declaration//GEN-END:variables
}
